// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaVYNaFkSDjW9y21RflrozYWjWmwQHuYo',
    appId: '1:653084229146:web:0d53cac896ceebf8c99ba3',
    messagingSenderId: '653084229146',
    projectId: 'click-book-3a239',
    authDomain: 'click-book-3a239.firebaseapp.com',
    storageBucket: 'click-book-3a239.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUBTsfoXyzREesHDm03taB8cTJ7dk_JfI',
    appId: '1:653084229146:android:3a9a7c351a17b04cc99ba3',
    messagingSenderId: '653084229146',
    projectId: 'click-book-3a239',
    storageBucket: 'click-book-3a239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGajmtLfc1K5LwHN3Bj6tkeLMwLcpZ8fo',
    appId: '1:653084229146:ios:d2ddc329d510a385c99ba3',
    messagingSenderId: '653084229146',
    projectId: 'click-book-3a239',
    storageBucket: 'click-book-3a239.firebasestorage.app',
    iosBundleId: 'com.example.clickandbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGajmtLfc1K5LwHN3Bj6tkeLMwLcpZ8fo',
    appId: '1:653084229146:ios:d2ddc329d510a385c99ba3',
    messagingSenderId: '653084229146',
    projectId: 'click-book-3a239',
    storageBucket: 'click-book-3a239.firebasestorage.app',
    iosBundleId: 'com.example.clickandbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaVYNaFkSDjW9y21RflrozYWjWmwQHuYo',
    appId: '1:653084229146:web:a87d092f818212d8c99ba3',
    messagingSenderId: '653084229146',
    projectId: 'click-book-3a239',
    authDomain: 'click-book-3a239.firebaseapp.com',
    storageBucket: 'click-book-3a239.firebasestorage.app',
  );
}
